// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Presentation = require("./Presentation.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Presentation.make(/* array */[])), "index");

/*  Not a pure module */
