// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Heading$BsSpectacle = require("bs-spectacle/src/components/Heading.js");

function s(prim) {
  return prim;
}

var component = ReasonReact.reducerComponent("Interactive");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (param) {
      var state = param[/* state */2];
      var match = +(state < 5);
      return React.createElement("div", undefined, match !== 0 ? React.createElement("div", undefined, ReasonReact.element(/* None */0, /* None */0, Heading$BsSpectacle.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */["black"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[5], /* None */0, /* None */0, /* array */["The button has been clicked " + (String(state) + " times")])), React.createElement("button", {
                            style: {
                              background: "black",
                              border: "none",
                              color: "white",
                              fontFamily: "inherit",
                              fontSize: "2em",
                              fontWeight: "bold",
                              marginTop: "20px",
                              minWidth: "300px",
                              outline: "none",
                              padding: "20px",
                              textTransform: "uppercase"
                            },
                            type: "button",
                            onClick: Curry._1(param[/* reduce */1], (function () {
                                    return /* Increment */0;
                                  }))
                          }, "Click Me")) : ReasonReact.element(/* None */0, /* None */0, Heading$BsSpectacle.make(/* None */0, /* None */0, /* Some */[/* true */1], /* None */0, /* None */0, /* Some */["black"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[5], /* Some */[/* true */1], /* None */0, /* array */["Easy there pal"])));
    });
  newrecord[/* initialState */10] = (function () {
      return 0;
    });
  newrecord[/* reducer */12] = (function (_, state) {
      return /* Update */Block.__(0, [state + 1 | 0]);
    });
  return newrecord;
}

exports.s = s;
exports.component = component;
exports.make = make;
/* component Not a pure module */
