// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function map(f, x) {
  if (x) {
    return /* Some */[Curry._1(f, x[0])];
  } else {
    return /* None */0;
  }
}

exports.map = map;
/* No side effect */
