// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Js_boolean = require("bs-platform/lib/js/js_boolean.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");

function map(f, x) {
  if (x) {
    return /* Some */[Curry._1(f, x[0])];
  } else {
    return /* None */0;
  }
}

function to_js_boolean(a) {
  return Js_null_undefined.fromOption(map(Js_boolean.to_js_boolean, a));
}

exports.map = map;
exports.to_js_boolean = to_js_boolean;
/* No side effect */
