// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");

var jsMapperConstantArray = /* array */[
  /* tuple */[
    -922086728,
    "none"
  ],
  /* tuple */[
    -476456824,
    "pacman"
  ],
  /* tuple */[
    4895187,
    "bar"
  ],
  /* tuple */[
    561678025,
    "number"
  ]
];

function progressToJs(param) {
  return Js_mapperRt.binSearch(4, param, jsMapperConstantArray);
}

function progressFromJs(param) {
  return Js_mapperRt.revSearch(4, jsMapperConstantArray, param);
}

var jsMapperConstantArray$1 = /* array */[
  /* tuple */[
    -1011501700,
    "fade"
  ],
  /* tuple */[
    -866590270,
    "spin"
  ],
  /* tuple */[
    -789011693,
    "zoom"
  ],
  /* tuple */[
    -20462287,
    "slide"
  ]
];

function transitionToJs(param) {
  return Js_mapperRt.binSearch(4, param, jsMapperConstantArray$1);
}

function transitionFromJs(param) {
  return Js_mapperRt.revSearch(4, jsMapperConstantArray$1, param);
}

exports.progressToJs     = progressToJs;
exports.progressFromJs   = progressFromJs;
exports.transitionToJs   = transitionToJs;
exports.transitionFromJs = transitionFromJs;
/* No side effect */
