// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


var deck = "return (\n    <Deck transition={[\'zoom\',\'slide\']} transitionDuration={800}>\n      <Slide bgColor=\"primary\">\n        <Heading size={1} fit caps>\n          React Presentations\n        </Heading>\n        <Heading size={2} fit caps>\n          Written In React\n        </Heading>\n      </Slide>\n      <Slide bgColor=\"black\">\n        <Heading size={1} fit textColor=\"primary\" textFont=\"secondary\">\n          Wait What?\n        </Heading>\n      </Slide>\n      <Slide bgColor=\"primary\" textColor=\"black\" align=\"center top\">\n        <Heading size={1} textColor=\"black\" textFont=\"primary\">\n          Thats right\n        </Heading>\n        <List>\n          <ListItem>Inline style based theme system</ListItem>\n          <ListItem>Autofit Text</ListItem>\n          <ListItem>PDF Export</ListItem>\n        </List>\n      </Slide>\n    </Deck>\n  )\n  ";

exports.deck = deck;
/* No side effect */
