// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Block                           = require("bs-platform/lib/js/block.js");
var Curry                           = require("bs-platform/lib/js/curry.js");
var React                           = require("react");
var Examples                        = require("./Examples.js");
var ReasonReact                     = require("reason-react/src/ReasonReact.js");
var Cite$BsSpectacle                = require("bs-spectacle/src/components/Cite.js");
var Deck$BsSpectacle                = require("bs-spectacle/src/components/Deck.js");
var Fill$BsSpectacle                = require("bs-spectacle/src/components/Fill.js");
var Link$BsSpectacle                = require("bs-spectacle/src/components/Link.js");
var Text$BsSpectacle                = require("bs-spectacle/src/components/Text.js");
var Image$BsSpectacle               = require("bs-spectacle/src/components/Image.js");
var Quote$BsSpectacle               = require("bs-spectacle/src/components/Quote.js");
var Slide$BsSpectacle               = require("bs-spectacle/src/components/Slide.js");
var Theme$BsSpectacle               = require("bs-spectacle/src/Theme.js");
var Appear$BsSpectacle              = require("bs-spectacle/src/components/Appear.js");
var Layout$BsSpectacle              = require("bs-spectacle/src/components/Layout.js");
var Heading$BsSpectacle             = require("bs-spectacle/src/components/Heading.js");
var CodePane$BsSpectacle            = require("bs-spectacle/src/components/CodePane.js");
var Markdown$BsSpectacle            = require("bs-spectacle/src/components/Markdown.js");
var BlockQuote$BsSpectacle          = require("bs-spectacle/src/components/BlockQuote.js");
var GoToAction$BsSpectacle          = require("bs-spectacle/src/components/GoToAction.js");
var ComponentPlayground$BsSpectacle = require("bs-spectacle/src/components/ComponentPlayground.js");

var theme = Theme$BsSpectacle.createTheme(/* record */[
      /* primary */"#ff4081",
      /* secondary */"black",
      /* tertiary */"white",
      /* quarternary */"white"
    ], /* record */[
      /* primary : record */[
        /* name */"Open Sans Condensed",
        /* googleFont : true */1,
        /* styles : array */[
          "300",
          "700"
        ]
      ],
      /* secondary : record */[
        /* name */"Lobster Two",
        /* googleFont : true */1,
        /* styles : array */[
          "400",
          "700"
        ]
      ],
      /* tertiary */Theme$BsSpectacle.simpleFont("monospace")
    ]);

var images_000 = /* city */( require('./assets/city.jpg'));

var images_001 = /* kat */( require('./assets/kat.png'));

var images_002 = /* logo */( require('./assets/formidable-logo.svg'));

var images_003 = /* markdown */( require('./assets/markdown.png'));

var images = /* record */[
  images_000,
  images_001,
  images_002,
  images_003
];

function s(prim) {
  return prim;
}

var component = ReasonReact.reducerComponent("Presentation");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (param) {
      var state = param[/* state */2];
      var markdownLogo = images_003;
      return ReasonReact.element(/* None */0, /* None */0, Deck$BsSpectacle.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[theme], /* Some */[/* array */[
                        /* zoom */-789011693,
                        /* slide */-20462287
                      ]], /* Some */[500], /* None */0, /* None */0, /* array */[
                      ReasonReact.element(/* None */0, /* None */0, Slide$BsSpectacle.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */["primary"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[/* array */[/* zoom */-789011693]], /* None */0, /* None */0, /* None */0, /* None */0, /* array */[
                                ReasonReact.element(/* None */0, /* None */0, Heading$BsSpectacle.make(/* None */0, /* None */0, /* Some */[/* true */1], /* None */0, /* None */0, /* Some */["black"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[1], /* Some */[/* true */1], /* Some */[1.0], /* array */["Spectacle"])),
                                ReasonReact.element(/* None */0, /* None */0, Heading$BsSpectacle.make(/* None */0, /* None */0, /* Some */[/* true */1], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[1], /* Some */[/* true */1], /* None */0, /* array */["A ReactJS Presentation Library"])),
                                ReasonReact.element(/* None */0, /* None */0, Heading$BsSpectacle.make(/* None */0, /* None */0, /* Some */[/* true */1], /* None */0, /* None */0, /* Some */["black"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[1], /* Some */[/* true */1], /* None */0, /* array */["Where You Can Write Your Decks In JSX"])),
                                ReasonReact.element(/* None */0, /* None */0, Link$BsSpectacle.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, "https://github.com/FormidableLabs/spectacle", /* None */0, /* array */[ReasonReact.element(/* None */0, /* None */0, Text$BsSpectacle.make(/* None */0, /* Some */[/* true */1], /* Some */[/* true */1], /* None */0, /* None */0, /* Some */["tertiary"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */["View on Github"]))])),
                                ReasonReact.element(/* None */0, /* None */0, Text$BsSpectacle.make(/* None */0, /* Some */[/* true */1], /* None */0, /* Some */["20px 0px 0px"], /* None */0, /* None */0, /* Some */["1.5em"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */["Hit Your Right Arrow To Begin!"]))
                              ])),
                      ReasonReact.element(/* None */0, /* None */0, Slide$BsSpectacle.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */["black"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[4], /* Some */["wait-what"], /* None */0, /* None */0, /* Some */["You can even put notes on your slide. How awesome is that?"], /* Some */[(function (slideIndex) {
                                    console.log("Viewing slide index: " + (String(slideIndex) + ""));
                                    return /* () */0;
                                  })], /* None */0, /* Some */[/* array */[/* fade */-1011501700]], /* None */0, /* None */0, /* None */0, /* None */0, /* array */[
                                ReasonReact.element(/* None */0, /* None */0, Image$BsSpectacle.make(/* None */0, /* None */0, /* None */0, /* Some */["0px auto 40px"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, images_001, /* None */0, /* None */0, /* None */0, /* None */0, /* array */[])),
                                ReasonReact.element(/* None */0, /* None */0, Heading$BsSpectacle.make(/* None */0, /* None */0, /* Some */[/* true */1], /* None */0, /* None */0, /* Some */["primary"], /* None */0, /* None */0, /* Some */["primary"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[2], /* Some */[/* true */1], /* None */0, /* array */["Wait what?"]))
                              ])),
                      ReasonReact.element(/* None */0, /* None */0, Slide$BsSpectacle.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */["primary"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */["<ul><li>talk about that</li><li>and that</li></ul>"], /* None */0, /* None */0, /* None */0, /* Some */[/* array */[
                                  /* zoom */-789011693,
                                  /* fade */-1011501700
                                ]], /* Some */[/* array */[
                                  /* slide */-20462287,
                                  /* fade */-1011501700
                                ]], /* None */0, /* None */0, /* array */[ReasonReact.element(/* None */0, /* None */0, CodePane$BsSpectacle.make(/* None */0, /* None */0, /* None */0, /* Some */["20px auto"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */["overflow"], "jsx", Examples.deck, /* array */[]))])),
                      ReasonReact.element(/* None */0, /* None */0, Slide$BsSpectacle.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[3], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */[ReasonReact.element(/* None */0, /* None */0, ComponentPlayground$BsSpectacle.make(/* None */0, /* None */0, /* Some */[/* dark */-1033677706], /* None */0, /* array */[]))])),
                      ReasonReact.element(/* None */0, /* None */0, Slide$BsSpectacle.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[images_000], /* None */0, /* None */0, /* None */0, /* Some */[0.75], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[/* array */[/* slide */-20462287]], /* None */0, /* None */0, /* None */0, /* None */0, /* array */[
                                ReasonReact.element(/* None */0, /* None */0, Appear$BsSpectacle.make(/* None */0, /* Some */["1"], /* array */[ReasonReact.element(/* None */0, /* None */0, Heading$BsSpectacle.make(/* None */0, /* None */0, /* Some */[/* true */1], /* None */0, /* None */0, /* Some */["primary"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[1], /* Some */[/* true */1], /* None */0, /* array */["Full Width"]))])),
                                ReasonReact.element(/* None */0, /* None */0, Appear$BsSpectacle.make(/* None */0, /* Some */["2"], /* array */[ReasonReact.element(/* None */0, /* None */0, Heading$BsSpectacle.make(/* None */0, /* None */0, /* Some */[/* true */1], /* None */0, /* None */0, /* Some */["tertiary"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[1], /* Some */[/* true */1], /* None */0, /* array */["Adjustable Darkness"]))])),
                                ReasonReact.element(/* None */0, /* None */0, Appear$BsSpectacle.make(/* None */0, /* Some */["3"], /* array */[ReasonReact.element(/* None */0, /* None */0, Heading$BsSpectacle.make(/* None */0, /* None */0, /* Some */[/* true */1], /* None */0, /* None */0, /* Some */["primary"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[1], /* Some */[/* true */1], /* None */0, /* array */["Background Imagery"]))]))
                              ])),
                      ReasonReact.element(/* None */0, /* None */0, Slide$BsSpectacle.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */[
                                ReasonReact.element(/* None */0, /* None */0, Heading$BsSpectacle.make(/* None */0, /* None */0, /* None */0, /* Some */["0.25em"], /* None */0, /* Some */["secondary"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[2], /* None */0, /* None */0, /* array */["Mix it up!"])),
                                ReasonReact.element(/* None */0, /* None */0, Heading$BsSpectacle.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */["tertiary"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[6], /* None */0, /* None */0, /* array */["You can even jump to different slides with a standard button or custom component!"])),
                                ReasonReact.element(/* None */0, /* None */0, GoToAction$BsSpectacle.make(/* None */0, /* None */0, /* None */0, /* Some */["1em"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[8], /* None */0, /* array */["Jump to Slide 8"])),
                                ReasonReact.element(/* None */0, /* None */0, GoToAction$BsSpectacle.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[(function (goToSlide) {
                                              return React.createElement("select", {
                                                          defaultValue: "",
                                                          style: {
                                                            background: "#000",
                                                            color: "#fff",
                                                            fontFamily: "Open Sans Condensed",
                                                            fontSize: "1.1em"
                                                          },
                                                          onChange: (function ($$event) {
                                                              return Curry._1(goToSlide, $$event.target.value);
                                                            })
                                                        }, React.createElement("option", {
                                                              disabled: true,
                                                              value: ""
                                                            }, "Custom Slide Picker"), React.createElement("option", {
                                                              value: "wait-what"
                                                            }, "Wait What!? Slide"), React.createElement("option", {
                                                              value: "3"
                                                            }, "Slide 3"));
                                            })], /* array */[]))
                              ])),
                      ReasonReact.element(/* None */0, /* None */0, Slide$BsSpectacle.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[0.75], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[/* array */[/* slide */-20462287]], /* None */0, /* None */0, /* None */0, /* Some */[Curry._1(param[/* reduce */1], (function (steps) {
                                        var match = +(state[/* steps */0] !== steps);
                                        if (match !== 0) {
                                          return /* UpdateSteps */[steps];
                                        } else {
                                          return /* NoUpdate */0;
                                        }
                                      }))], /* array */[
                                ReasonReact.element(/* None */0, /* None */0, Appear$BsSpectacle.make(/* None */0, /* None */0, /* array */[ReasonReact.element(/* None */0, /* None */0, Heading$BsSpectacle.make(/* None */0, /* None */0, /* Some */[/* true */1], /* None */0, /* None */0, /* Some */["tertiary"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[1], /* None */0, /* None */0, /* array */["Can"]))])),
                                ReasonReact.element(/* None */0, /* None */0, Appear$BsSpectacle.make(/* None */0, /* None */0, /* array */[ReasonReact.element(/* None */0, /* None */0, Heading$BsSpectacle.make(/* None */0, /* None */0, /* Some */[/* true */1], /* None */0, /* None */0, /* Some */["secondary"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[1], /* None */0, /* None */0, /* array */["Count"]))])),
                                ReasonReact.element(/* None */0, /* None */0, Appear$BsSpectacle.make(/* None */0, /* None */0, /* array */[ReasonReact.element(/* None */0, /* None */0, Heading$BsSpectacle.make(/* None */0, /* None */0, /* Some */[/* true */1], /* None */0, /* None */0, /* Some */["tertiary"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[1], /* None */0, /* None */0, /* array */["Steps"]))])),
                                ReasonReact.element(/* None */0, /* None */0, Heading$BsSpectacle.make(/* None */0, /* None */0, /* Some */[/* true */1], /* None */0, /* None */0, /* Some */["secondary"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[1], /* Some */[/* true */1], /* None */0, /* array */["Steps: " + (String(state) + "")]))
                              ])),
                      ReasonReact.element(/* None */0, /* None */0, Slide$BsSpectacle.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */["primary"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[/* array */[
                                  /* zoom */-789011693,
                                  /* fade */-1011501700
                                ]], /* None */0, /* None */0, /* None */0, /* None */0, /* array */[
                                ReasonReact.element(/* None */0, /* None */0, Heading$BsSpectacle.make(/* None */0, /* None */0, /* Some */[/* true */1], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[/* true */1], /* None */0, /* array */["Flexible Layouts"])),
                                ReasonReact.element(/* None */0, /* None */0, Layout$BsSpectacle.make(/* array */[
                                          ReasonReact.element(/* None */0, /* None */0, Fill$BsSpectacle.make(/* array */[ReasonReact.element(/* None */0, /* None */0, Heading$BsSpectacle.make(/* None */0, /* None */0, /* Some */[/* true */1], /* Some */["10"], /* None */0, /* Some */["secondary"], /* None */0, /* None */0, /* None */0, /* Some */["white"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[4], /* None */0, /* None */0, /* array */["Left"]))])),
                                          ReasonReact.element(/* None */0, /* None */0, Fill$BsSpectacle.make(/* array */[ReasonReact.element(/* None */0, /* None */0, Heading$BsSpectacle.make(/* None */0, /* None */0, /* Some */[/* true */1], /* Some */["10"], /* None */0, /* Some */["secondary"], /* None */0, /* None */0, /* None */0, /* Some */["white"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[4], /* None */0, /* None */0, /* array */["Right"]))]))
                                        ]))
                              ])),
                      ReasonReact.element(/* None */0, /* None */0, Slide$BsSpectacle.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */["black"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[/* array */[/* slide */-20462287]], /* None */0, /* None */0, /* None */0, /* None */0, /* array */[ReasonReact.element(/* None */0, /* None */0, BlockQuote$BsSpectacle.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */[
                                          ReasonReact.element(/* None */0, /* None */0, Quote$BsSpectacle.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */["Wonderfully formatted quotes"])),
                                          ReasonReact.element(/* None */0, /* None */0, Cite$BsSpectacle.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */["Ken Wheeler"]))
                                        ]))])),
                      ReasonReact.element(/* None */0, /* None */0, Slide$BsSpectacle.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */["tertiary"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */["primary"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */["primary"], /* Some */[/* array */[
                                  /* spin */-866590270,
                                  /* zoom */-789011693
                                ]], /* None */0, /* None */0, /* None */0, /* None */0, /* array */[
                                ReasonReact.element(/* None */0, /* None */0, Heading$BsSpectacle.make(/* None */0, /* None */0, /* Some */[/* true */1], /* None */0, /* None */0, /* Some */["primary"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[1], /* Some */[/* true */1], /* None */0, /* array */["Inline Markdown"])),
                                ReasonReact.element(/* None */0, /* None */0, Markdown$BsSpectacle.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */["\n![Markdown Logo](" + (String(markdownLogo) + ")\nYou can write inline images, [Markdown Links](http://commonmark.org), paragraph text and most other markdown syntax\n* Lists too!\n* With ~~strikethrough~~ and _italic_\n* And let\'s not forget **bold**")], /* array */[]))
                              ]))
                    ]));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* steps */0];
    });
  newrecord[/* reducer */12] = (function (action, _) {
      if (action) {
        return /* Update */Block.__(0, [/* record */[/* steps */action[0]]]);
      } else {
        return /* NoUpdate */0;
      }
    });
  return newrecord;
}

exports.theme     = theme;
exports.images    = images;
exports.s         = s;
exports.component = component;
exports.make      = make;
/* theme Not a pure module */
