// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Spectacle = require("spectacle");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");

function make(order, fid, children) {
  return ReasonReact.wrapJsForReason(Spectacle.Appear, {
              order: Js_null_undefined.fromOption(order),
              fid: Js_null_undefined.fromOption(fid)
            }, children);
}

exports.make = make;
/* spectacle Not a pure module */
