// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Spectacle = require("spectacle");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

function make(order, fid, children) {
  var tmp = { };
  if (order) {
    tmp.order = order[0];
  }
  if (fid) {
    tmp.fid = fid[0];
  }
  return ReasonReact.wrapJsForReason(Spectacle.Appear, tmp, children);
}

exports.make = make;
/* spectacle Not a pure module */
