// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Spectacle   = require("spectacle");
var Js_boolean  = require("bs-platform/lib/js/js_boolean.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

function make(history, theme, children) {
  return ReasonReact.wrapJsForReason(Spectacle.Spectacle, {
              theme: theme,
              history: history
            }, children);
}

function make$1($staropt$star, $staropt$star$1, $staropt$star$2, $staropt$star$3, children) {
  var ordered = $staropt$star ? $staropt$star[0] : /* false */0;
  var reversed = $staropt$star$1 ? $staropt$star$1[0] : /* false */0;
  var start = $staropt$star$2 ? $staropt$star$2[0] : 1;
  var type_ = $staropt$star$3 ? $staropt$star$3[0] : "1";
  return ReasonReact.wrapJsForReason(Spectacle.List, {
              ordered: Js_boolean.to_js_boolean(ordered),
              reversed: Js_boolean.to_js_boolean(reversed),
              start: start,
              type: type_
            }, children);
}

var List = /* module */[/* make */make$1];

function make$2(children) {
  return ReasonReact.wrapJsForReason(Spectacle.Notes, { }, children);
}

var Notes = /* module */[/* make */make$2];

exports.make  = make;
exports.List  = List;
exports.Notes = Notes;
/* spectacle Not a pure module */
