// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Spectacle = require("spectacle");
var BaseProps$BsSpectacle = require("../BaseProps.js");

var include = BaseProps$BsSpectacle.MakeBaseComponent(/* module */[/* Cite */Spectacle.Cite]);

var make = include[0];

exports.make = make;
/* include Not a pure module */
