// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Spectacle = require("spectacle");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");
var Option$BsSpectacle = require("../Option.js");

function componentPlaygroundThemeToJs(theme) {
  if (theme !== 0) {
    return "dark";
  } else {
    return "light";
  }
}

function make(code, previewBackgroundColor, theme, scope, children) {
  return ReasonReact.wrapJsForReason(Spectacle.ComponentPlayground, {
              code: Js_null_undefined.fromOption(code),
              previewBackgroundColor: Js_null_undefined.fromOption(previewBackgroundColor),
              theme: Js_null_undefined.fromOption(Option$BsSpectacle.map(componentPlaygroundThemeToJs, theme)),
              scope: Js_null_undefined.fromOption(scope)
            }, children);
}

exports.componentPlaygroundThemeToJs = componentPlaygroundThemeToJs;
exports.make = make;
/* spectacle Not a pure module */
