// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Spectacle         = require("spectacle");
var ReasonReact       = require("reason-react/lib/js/src/ReasonReact.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");

function make(code, previewBackgroundColor, theme, scope, children) {
  return ReasonReact.wrapJsForReason(Spectacle.ComponentPlayground, {
              code: Js_null_undefined.from_opt(code),
              previewBackgroundColor: Js_null_undefined.from_opt(previewBackgroundColor),
              theme: Js_null_undefined.from_opt(theme),
              scope: Js_null_undefined.from_opt(scope)
            }, children);
}

exports.make = make;
/* spectacle Not a pure module */
