// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Spectacle = require("spectacle");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");
var Types$BsSpectacle = require("../Types.js");
var Option$BsSpectacle = require("../Option.js");

function make(controls, contentHeight, contentWidth, history, progress, theme, $staropt$star, transitionDuration, autoplay, autoplayDuration, children) {
  var transition = $staropt$star ? $staropt$star[0] : /* array */[];
  return ReasonReact.wrapJsForReason(Spectacle.Deck, {
              controls: Option$BsSpectacle.to_js_boolean(controls),
              contentHeight: Js_null_undefined.fromOption(contentHeight),
              contentWidth: Js_null_undefined.fromOption(contentWidth),
              history: Js_null_undefined.fromOption(history),
              progress: Option$BsSpectacle.map(Types$BsSpectacle.progressToJs, progress),
              theme: Js_null_undefined.fromOption(theme),
              transition: $$Array.map(Types$BsSpectacle.transitionToJs, transition),
              transitionDuration: Js_null_undefined.fromOption(transitionDuration),
              autoplay: Option$BsSpectacle.to_js_boolean(autoplay),
              autoplayDuration: Js_null_undefined.fromOption(autoplayDuration)
            }, children);
}

exports.make = make;
/* spectacle Not a pure module */
