// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array           = require("bs-platform/lib/js/array.js");
var Spectacle         = require("spectacle");
var ReasonReact       = require("reason-react/lib/js/src/ReasonReact.js");
var Types$Spectacle   = require("../Types.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");

function make(controls, contentHeight, contentWidth, history, $staropt$star, theme, $staropt$star$1, transitionDuration, autoplay, autoplayDuration, children) {
  var progress = $staropt$star ? $staropt$star[0] : /* pacman */-476456824;
  var transition = $staropt$star$1 ? $staropt$star$1[0] : /* array */[];
  return ReasonReact.wrapJsForReason(Spectacle.Deck, {
              controls: Js_null_undefined.from_opt(controls),
              contentHeight: Js_null_undefined.from_opt(contentHeight),
              contentWidth: Js_null_undefined.from_opt(contentWidth),
              history: Js_null_undefined.from_opt(history),
              progress: Types$Spectacle.progressToJs(progress),
              theme: Js_null_undefined.from_opt(theme),
              transition: $$Array.map(Types$Spectacle.transitionToJs, transition),
              transitionDuration: Js_null_undefined.from_opt(transitionDuration),
              autoplay: Js_null_undefined.from_opt(autoplay),
              autoplayDuration: Js_null_undefined.from_opt(autoplayDuration)
            }, children);
}

exports.make = make;
/* spectacle Not a pure module */
