// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Spectacle = require("spectacle");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

function make(children) {
  return ReasonReact.wrapJsForReason(Spectacle.Fill, { }, children);
}

exports.make = make;
/* spectacle Not a pure module */
