// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Spectacle         = require("spectacle");
var ReasonReact       = require("reason-react/lib/js/src/ReasonReact.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");

function make(italic, bold, caps, margin, padding, textColor, textSize, textAlign, textFont, bgColor, bgImage, bgSize, bgPosition, bgRepeat, bgDarken, overflow, height, slide, render, children) {
  return ReasonReact.wrapJsForReason(Spectacle.GoToAction, {
              italic: Js_null_undefined.from_opt(italic),
              bold: Js_null_undefined.from_opt(bold),
              caps: Js_null_undefined.from_opt(caps),
              margin: Js_null_undefined.from_opt(margin),
              padding: Js_null_undefined.from_opt(padding),
              textColor: Js_null_undefined.from_opt(textColor),
              textSize: Js_null_undefined.from_opt(textSize),
              textAlign: Js_null_undefined.from_opt(textAlign),
              textFont: Js_null_undefined.from_opt(textFont),
              bgColor: Js_null_undefined.from_opt(bgColor),
              bgImage: Js_null_undefined.from_opt(bgImage),
              bgSize: Js_null_undefined.from_opt(bgSize),
              bgPosition: Js_null_undefined.from_opt(bgPosition),
              bgRepeat: Js_null_undefined.from_opt(bgRepeat),
              bgDarken: Js_null_undefined.from_opt(bgDarken),
              overflow: Js_null_undefined.from_opt(overflow),
              height: Js_null_undefined.from_opt(height),
              slide: Js_null_undefined.from_opt(slide),
              render: Js_null_undefined.from_opt(render)
            }, children);
}

exports.make = make;
/* spectacle Not a pure module */
