// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Spectacle = require("spectacle");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");
var Option$BsSpectacle = require("../Option.js");

function make(italic, bold, caps, margin, padding, textColor, textSize, textAlign, textFont, bgColor, bgImage, bgSize, bgPosition, bgRepeat, bgDarken, overflow, height, ordered, reversed, start, type_, children) {
  return ReasonReact.wrapJsForReason(Spectacle.List, {
              italic: Option$BsSpectacle.to_js_boolean(italic),
              bold: Option$BsSpectacle.to_js_boolean(bold),
              caps: Option$BsSpectacle.to_js_boolean(caps),
              margin: Js_null_undefined.fromOption(margin),
              padding: Js_null_undefined.fromOption(padding),
              textColor: Js_null_undefined.fromOption(textColor),
              textSize: Js_null_undefined.fromOption(textSize),
              textAlign: Js_null_undefined.fromOption(textAlign),
              textFont: Js_null_undefined.fromOption(textFont),
              bgColor: Js_null_undefined.fromOption(bgColor),
              bgImage: Js_null_undefined.fromOption(bgImage),
              bgSize: Js_null_undefined.fromOption(bgSize),
              bgPosition: Js_null_undefined.fromOption(bgPosition),
              bgRepeat: Js_null_undefined.fromOption(bgRepeat),
              bgDarken: Js_null_undefined.fromOption(bgDarken),
              overflow: Js_null_undefined.fromOption(overflow),
              height: Js_null_undefined.fromOption(height),
              ordered: Option$BsSpectacle.to_js_boolean(ordered),
              reversed: Option$BsSpectacle.to_js_boolean(reversed),
              start: Js_null_undefined.fromOption(start),
              type_: Js_null_undefined.fromOption(type_)
            }, children);
}

exports.make = make;
/* spectacle Not a pure module */
