// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Spectacle = require("spectacle");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Types$BsSpectacle = require("../Types.js");
var BaseProps$BsSpectacle = require("../BaseProps.js");

function make(italic, bold, caps, margin, padding, textColor, textSize, textAlign, textFont, bgColor, bgImage, bgSize, bgPosition, bgRepeat, bgDarken, overflow, height, ordered, reversed, start, type_, children) {
  var tmp = { };
  var tmp$1 = Types$BsSpectacle.to_js_boolean(ordered);
  if (tmp$1) {
    tmp.ordered = tmp$1[0];
  }
  var tmp$2 = Types$BsSpectacle.to_js_boolean(reversed);
  if (tmp$2) {
    tmp.reversed = tmp$2[0];
  }
  if (start) {
    tmp.start = start[0];
  }
  if (type_) {
    tmp.type = type_[0];
  }
  return ReasonReact.wrapJsForReason(Spectacle.List, BaseProps$BsSpectacle.extendProps(italic, bold, caps, margin, padding, textColor, textSize, textAlign, textFont, bgColor, bgImage, bgSize, bgPosition, bgRepeat, bgDarken, overflow, height, tmp), children);
}

exports.make = make;
/* spectacle Not a pure module */
