// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Spectacle = require("spectacle");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var BaseProps$BsSpectacle = require("../BaseProps.js");

function make(italic, bold, caps, margin, padding, textColor, textSize, textAlign, textFont, bgColor, bgImage, bgSize, bgPosition, bgRepeat, bgDarken, overflow, height, source, children) {
  var tmp = { };
  if (source) {
    tmp.source = source[0];
  }
  return ReasonReact.wrapJsForReason(Spectacle.Markdown, BaseProps$BsSpectacle.extendProps(italic, bold, caps, margin, padding, textColor, textSize, textAlign, textFont, bgColor, bgImage, bgSize, bgPosition, bgRepeat, bgDarken, overflow, height, tmp), children);
}

exports.make = make;
/* spectacle Not a pure module */
