// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Spectacle          = require("spectacle");
var Js_mapperRt        = require("bs-platform/lib/js/js_mapperRt.js");
var ReasonReact        = require("reason-react/lib/js/src/ReasonReact.js");
var Js_null_undefined  = require("bs-platform/lib/js/js_null_undefined.js");
var Option$BsSpectacle = require("../Option.js");

var jsMapperConstantArray = /* array */[
  /* tuple */[
    -1055161979,
    "bold"
  ],
  /* tuple */[
    -136827821,
    "strikethrough"
  ],
  /* tuple */[
    107228912,
    "italic"
  ],
  /* tuple */[
    131142924,
    "underline"
  ]
];

function sTypeToJs(param) {
  return Js_mapperRt.binSearch(4, param, jsMapperConstantArray);
}

function sTypeFromJs(param) {
  return Js_mapperRt.revSearch(4, jsMapperConstantArray, param);
}

function make(italic, bold, caps, margin, padding, textColor, textSize, textAlign, textFont, bgColor, bgImage, bgSize, bgPosition, bgRepeat, bgDarken, overflow, height, type_, children) {
  return ReasonReact.wrapJsForReason(Spectacle.S, {
              italic: Option$BsSpectacle.to_js_boolean(italic),
              bold: Option$BsSpectacle.to_js_boolean(bold),
              caps: Option$BsSpectacle.to_js_boolean(caps),
              margin: Js_null_undefined.from_opt(margin),
              padding: Js_null_undefined.from_opt(padding),
              textColor: Js_null_undefined.from_opt(textColor),
              textSize: Js_null_undefined.from_opt(textSize),
              textAlign: Js_null_undefined.from_opt(textAlign),
              textFont: Js_null_undefined.from_opt(textFont),
              bgColor: Js_null_undefined.from_opt(bgColor),
              bgImage: Js_null_undefined.from_opt(bgImage),
              bgSize: Js_null_undefined.from_opt(bgSize),
              bgPosition: Js_null_undefined.from_opt(bgPosition),
              bgRepeat: Js_null_undefined.from_opt(bgRepeat),
              bgDarken: Js_null_undefined.from_opt(bgDarken),
              overflow: Js_null_undefined.from_opt(overflow),
              height: Js_null_undefined.from_opt(height),
              type: Option$BsSpectacle.map(sTypeToJs, type_)
            }, children);
}

exports.sTypeToJs   = sTypeToJs;
exports.sTypeFromJs = sTypeFromJs;
exports.make        = make;
/* spectacle Not a pure module */
