// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Spectacle = require("spectacle");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");
var Types$BsSpectacle = require("../Types.js");
var Option$BsSpectacle = require("../Option.js");

function make(italic, bold, caps, margin, padding, textColor, textSize, textAlign, textFont, bgColor, bgImage, bgSize, bgPosition, bgRepeat, bgDarken, overflow, height, align, controlColor, goTo, id, maxHeight, maxWidth, notes, onActive, progressColor, $staropt$star, $staropt$star$1, $staropt$star$2, transitionDuration, getAppearStep, children) {
  var transition = $staropt$star ? $staropt$star[0] : /* array */[];
  var transitionIn = $staropt$star$1 ? $staropt$star$1[0] : /* array */[];
  var transitionOut = $staropt$star$2 ? $staropt$star$2[0] : /* array */[];
  return ReasonReact.wrapJsForReason(Spectacle.Slide, {
              italic: Option$BsSpectacle.to_js_boolean(italic),
              bold: Option$BsSpectacle.to_js_boolean(bold),
              caps: Option$BsSpectacle.to_js_boolean(caps),
              margin: Js_null_undefined.fromOption(margin),
              padding: Js_null_undefined.fromOption(padding),
              textColor: Js_null_undefined.fromOption(textColor),
              textSize: Js_null_undefined.fromOption(textSize),
              textAlign: Js_null_undefined.fromOption(textAlign),
              textFont: Js_null_undefined.fromOption(textFont),
              bgColor: Js_null_undefined.fromOption(bgColor),
              bgImage: Js_null_undefined.fromOption(bgImage),
              bgSize: Js_null_undefined.fromOption(bgSize),
              bgPosition: Js_null_undefined.fromOption(bgPosition),
              bgRepeat: Js_null_undefined.fromOption(bgRepeat),
              bgDarken: Js_null_undefined.fromOption(bgDarken),
              overflow: Js_null_undefined.fromOption(overflow),
              height: Js_null_undefined.fromOption(height),
              align: Js_null_undefined.fromOption(align),
              controlColor: Js_null_undefined.fromOption(controlColor),
              goTo: Js_null_undefined.fromOption(goTo),
              id: Js_null_undefined.fromOption(id),
              maxHeight: Js_null_undefined.fromOption(maxHeight),
              maxWidth: Js_null_undefined.fromOption(maxWidth),
              notes: Js_null_undefined.fromOption(notes),
              onActive: Js_null_undefined.fromOption(onActive),
              progressColor: Js_null_undefined.fromOption(progressColor),
              transition: $$Array.map(Types$BsSpectacle.transitionToJs, transition),
              transitionIn: $$Array.map(Types$BsSpectacle.transitionToJs, transitionIn),
              transitionOut: $$Array.map(Types$BsSpectacle.transitionToJs, transitionOut),
              transitionDuration: Js_null_undefined.fromOption(transitionDuration),
              getAppearStep: Js_null_undefined.fromOption(getAppearStep)
            }, children);
}

exports.make = make;
/* spectacle Not a pure module */
