// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Spectacle = require("spectacle");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Types$BsSpectacle = require("../Types.js");
var BaseProps$BsSpectacle = require("../BaseProps.js");

function make(italic, bold, caps, margin, padding, textColor, textSize, textAlign, textFont, bgColor, bgImage, bgSize, bgPosition, bgRepeat, bgDarken, overflow, height, fit, lineHeight, children) {
  var tmp = { };
  var tmp$1 = Types$BsSpectacle.to_js_boolean(fit);
  if (tmp$1) {
    tmp.fit = tmp$1[0];
  }
  if (lineHeight) {
    tmp.lineHeight = lineHeight[0];
  }
  return ReasonReact.wrapJsForReason(Spectacle.Text, BaseProps$BsSpectacle.extendProps(italic, bold, caps, margin, padding, textColor, textSize, textAlign, textFont, bgColor, bgImage, bgSize, bgPosition, bgRepeat, bgDarken, overflow, height, tmp), children);
}

exports.make = make;
/* spectacle Not a pure module */
