// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Spectacle = require("spectacle");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");
var Option$BsSpectacle = require("../Option.js");

function make(font, googleFont, weight, italic, children) {
  return ReasonReact.wrapJsForReason(Spectacle.Typeface, {
              font: Js_null_undefined.fromOption(font),
              googleFont: Js_null_undefined.fromOption(googleFont),
              weight: Js_null_undefined.fromOption(weight),
              italic: Option$BsSpectacle.to_js_boolean(italic)
            }, children);
}

exports.make = make;
/* spectacle Not a pure module */
