// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Spectacle = require("spectacle");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Types$BsSpectacle = require("../Types.js");

function make(font, googleFont, weight, italic, children) {
  var tmp = { };
  if (font) {
    tmp.font = font[0];
  }
  if (googleFont) {
    tmp.googleFont = googleFont[0];
  }
  if (weight) {
    tmp.weight = weight[0];
  }
  var tmp$1 = Types$BsSpectacle.to_js_boolean(italic);
  if (tmp$1) {
    tmp.italic = tmp$1[0];
  }
  return ReasonReact.wrapJsForReason(Spectacle.Typeface, tmp, children);
}

exports.make = make;
/* spectacle Not a pure module */
