// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact            = require("reason-react/src/ReasonReact.js");
var Cite$BsSpectacle       = require("bs-spectacle/src/components/Cite.js");
var Deck$BsSpectacle       = require("bs-spectacle/src/components/Deck.js");
var Quote$BsSpectacle      = require("bs-spectacle/src/components/Quote.js");
var Slide$BsSpectacle      = require("bs-spectacle/src/components/Slide.js");
var Theme$BsSpectacle      = require("bs-spectacle/src/Theme.js");
var Heading$BsSpectacle    = require("bs-spectacle/src/components/Heading.js");
var BlockQuote$BsSpectacle = require("bs-spectacle/src/components/BlockQuote.js");

var theme = Theme$BsSpectacle.createTheme(/* record */[
      /* primary */"#26A0D1",
      /* secondary */"white",
      /* tertiary */"#505050",
      /* quarternary */"white"
    ], /* record */[
      /* primary : record */[
        /* name */"Merriweather",
        /* googleFont : true */1,
        /* styles : array */["300"]
      ],
      /* secondary : record */[
        /* name */"Roboto",
        /* googleFont : true */1,
        /* styles : array */["100"]
      ],
      /* tertiary */Theme$BsSpectacle.simpleFont("monospace")
    ]);

function s(prim) {
  return prim;
}

var component = ReasonReact.statelessComponent("Simple");

function customTransition(transitioning, forward, _) {
  var angle = forward !== 0 ? -180 : 180;
  var translateY = transitioning !== 0 ? 100 : 0;
  var rotation = transitioning !== 0 ? angle : 0;
  var transform = "\n    translate3d(0%, " + (String(translateY) + ("%, 0)\n    rotate(" + (String(rotation) + "deg)\n    ")));
  var backgroundColor = transitioning !== 0 ? "#000" : "#26A0D1";
  return {
          backgroundColor: backgroundColor,
          transform: transform
        };
}

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, Deck$BsSpectacle.make(/* None */0, /* None */0, /* None */0, /* None */0, /* Some */[theme], /* Some */[/* array */[
                        /* Zoom */1,
                        /* Slide */0,
                        /* Custom */[customTransition]
                      ]], /* None */0, /* None */0, /* None */0, /* array */[
                      ReasonReact.element(/* None */0, /* None */0, Slide$BsSpectacle.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */[ReasonReact.element(/* None */0, /* None */0, Heading$BsSpectacle.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */["secondary"], /* None */0, /* None */0, /* Some */["secondary"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */["Hello, world"]))])),
                      ReasonReact.element(/* None */0, /* None */0, Slide$BsSpectacle.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */["secondary"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[/* array */[/* Slide */0]], /* None */0, /* None */0, /* None */0, /* None */0, /* array */[ReasonReact.element(/* None */0, /* None */0, BlockQuote$BsSpectacle.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */[
                                          ReasonReact.element(/* None */0, /* None */0, Quote$BsSpectacle.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */["It’s easy, see..."])),
                                          ReasonReact.element(/* None */0, /* None */0, Cite$BsSpectacle.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */["Unknown"]))
                                        ]))]))
                    ]));
    });
  return newrecord;
}

exports.theme            = theme;
exports.s                = s;
exports.component        = component;
exports.customTransition = customTransition;
exports.make             = make;
/* theme Not a pure module */
